"""added transaction model

Revision ID: 0023b6e21b6a
Revises: b0494025d7b6
Create Date: 2022-04-04 13:39:13.784907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0023b6e21b6a"
down_revision = "b0494025d7b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.Boolean(), nullable=False),
        sa.Column("amount_transacted", sa.Float(), nullable=False),
        sa.Column("coin_price_at_time_of_transaction", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["Coin.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_coin",
        sa.Column("users", sa.Integer(), nullable=True),
        sa.Column("coin", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coin"],
            ["Coin.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users"],
            ["User.id"],
        ),
    )
    op.drop_table("association")
    op.add_column(
        "User",
        sa.Column("balance", sa.Integer(), server_default="10000", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "balance")
    op.create_table(
        "association",
        sa.Column("users", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("coin", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["coin"], ["Coin.id"], name="association_coin_fkey"),
        sa.ForeignKeyConstraint(["users"], ["User.id"], name="association_users_fkey"),
    )
    op.drop_table("user_coin")
    op.drop_table("Transactions")
    # ### end Alembic commands ###
