"""added more models

Revision ID: 4d0d2a401d6f
Revises: bc73cb377f55
Create Date: 2022-04-05 15:51:31.771712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d0d2a401d6f"
down_revision = "bc73cb377f55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), server_default="10000", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crypto_holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("coingecko_id", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("crypto_wallet_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crypto_wallet_id"],
            ["crypto_wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "coin", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "coin", "symbol", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "coin", "coingecko_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.add_column("transaction", sa.Column("wallet_id", sa.Integer(), nullable=False))
    op.drop_constraint("Transactions_user_id_fkey", "transaction", type_="foreignkey")
    op.create_foreign_key(
        "transaction_wallet_fkey", "transaction", "crypto_wallet", ["wallet_id"], ["id"]
    )
    op.drop_column("transaction", "user_id")
    op.drop_column("user", "balance")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "balance",
            sa.INTEGER(),
            server_default=sa.text("10000"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "transaction",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("transaction_wallet_fkey", "transaction", type_="foreignkey")
    op.create_foreign_key(
        "Transactions_user_id_fkey", "transaction", "user", ["user_id"], ["id"]
    )
    op.drop_column("transaction", "wallet_id")
    op.alter_column(
        "coin", "coingecko_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "coin", "symbol", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("coin", "name", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_table("crypto_holdings")
    op.drop_table("crypto_wallet")
    # ### end Alembic commands ###
