"""changed the name of transaction type to is_sale

Revision ID: 529fc9d91525
Revises: de9ff6bbc686
Create Date: 2022-04-06 14:23:06.859625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "529fc9d91525"
down_revision = "de9ff6bbc686"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transaction", "transaction_type", new_column_name="is_sale")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transaction", "is_sale", new_column_name="transaction_type")

    # ### end Alembic commands ###
