"""changing field attributes

Revision ID: 94311d0720a2
Revises: 9aa4ff5d32ef
Create Date: 2022-04-11 16:24:36.569684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94311d0720a2'
down_revision = '9aa4ff5d32ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scoreboardrecords_name_key', 'scoreboardrecords', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('scoreboardrecords_name_key', 'scoreboardrecords', ['name'])
    # ### end Alembic commands ###
