"""added discord_ids


Revision ID: 9a26fbe9e430
Revises: 7b35b66dc6b1
Create Date: 2022-10-04 13:10:45.775488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a26fbe9e430'
down_revision = '7b35b66dc6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('discord_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'user', ['discord_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'discord_id')
    # ### end Alembic commands ###
