"""added scorebaord and scoreboardrecords model

Revision ID: 9aa4ff5d32ef
Revises: bf63330956da
Create Date: 2022-04-11 15:23:18.689676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa4ff5d32ef'
down_revision = 'bf63330956da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoreboards',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('scoreboardrecords',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scoreboard_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('starting_wallet_balance', sa.Float(), nullable=False),
    sa.Column('ending_wallet_balance', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scoreboard_id'], ['scoreboards._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreboardrecords')
    op.drop_table('scoreboards')
    # ### end Alembic commands ###
