"""added user model

Revision ID: b0494025d7b6
Revises: 68b9022bd851
Create Date: 2022-03-30 17:00:52.003875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0494025d7b6"
down_revision = "68b9022bd851"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Coin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("symbol", sa.String(length=255), nullable=True),
        sa.Column("coingecko_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "association",
        sa.Column("users", sa.Integer(), nullable=True),
        sa.Column("coin", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coin"],
            ["Coin.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users"],
            ["User.id"],
        ),
    )
    op.drop_table("coin")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coin",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("symbol", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "coingecko_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="coin_pkey"),
    )
    op.drop_table("association")
    op.drop_table("User")
    op.drop_table("Coin")
    # ### end Alembic commands ###
