"""initial revision

Revision ID: b27db047a1b1
Revises: 
Create Date: 2025-03-30 02:37:20.879470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27db047a1b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('coingecko_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_discord_id'), 'user', ['discord_id'], unique=True)
    op.create_table('user_coin',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coin'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['users'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_coin')
    op.drop_index(op.f('ix_user_discord_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('coin')
    # ### end Alembic commands ###
