"""added historical wallet value model

Revision ID: bf63330956da
Revises: 529fc9d91525
Create Date: 2022-04-08 14:23:18.661504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf63330956da'
down_revision = '529fc9d91525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_wallet_values',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('crypto_wallet_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usd_balance', sa.Float(), nullable=False),
    sa.Column('holdings_balance', sa.Float(), nullable=False),
    sa.Column('total_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crypto_wallet_id'], ['crypto_wallet.id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_wallet_values')
    # ### end Alembic commands ###
