"""changed scoreboard records

Revision ID: d84984014d00
Revises: 94311d0720a2
Create Date: 2022-04-11 17:25:21.203262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84984014d00'
down_revision = '94311d0720a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoreboardrecords', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('scoreboardrecords', sa.Column('starting_wallet_balance_id', sa.Integer(), nullable=True))
    op.add_column('scoreboardrecords', sa.Column('ending_wallet_balance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scoreboardrecords', 'historical_wallet_values', ['starting_wallet_balance_id'], ['_id'])
    op.create_foreign_key(None, 'scoreboardrecords', 'historical_wallet_values', ['ending_wallet_balance_id'], ['_id'])
    op.create_foreign_key(None, 'scoreboardrecords', 'user', ['user_id'], ['id'])
    op.drop_column('scoreboardrecords', 'name')
    op.drop_column('scoreboardrecords', 'ending_wallet_balance')
    op.drop_column('scoreboardrecords', 'starting_wallet_balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoreboardrecords', sa.Column('starting_wallet_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('scoreboardrecords', sa.Column('ending_wallet_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('scoreboardrecords', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scoreboardrecords', type_='foreignkey')
    op.drop_constraint(None, 'scoreboardrecords', type_='foreignkey')
    op.drop_constraint(None, 'scoreboardrecords', type_='foreignkey')
    op.drop_column('scoreboardrecords', 'ending_wallet_balance_id')
    op.drop_column('scoreboardrecords', 'starting_wallet_balance_id')
    op.drop_column('scoreboardrecords', 'user_id')
    # ### end Alembic commands ###
