"""changing balance from int to float

Revision ID: de9ff6bbc686
Revises: 20358e0ceace
Create Date: 2022-04-06 14:20:39.740745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9ff6bbc686'
down_revision = '20358e0ceace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_wallet', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('10000'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_wallet', 'balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('10000'))
    # ### end Alembic commands ###
